export const DEFAULT_PARTS = [
  'Front Bumper',
  'Grill',
  'Head Lamp (LT/RT)',
  'Side Turn Light (LT/RT)',
  'Indicator Light (LT/RT)',
  'Fog Lamp (LT/RT)',
  'Front Panel',
  'Bonnet',
  'Left Apron',
  'Right Apron',
  'Left Front Fender',
  'Left Front Door',
  'Left Rear Door',
  'Left Pillar Front (A)',
  'Left Pillar Center (B)',
  'Left Pillar Rear (C)',
  'Left Running Board',
  'Left Qtr. Panel',
  'Boot',
  'Rear Bumper',
  'Tail lamp (LT/RT)',
  'Right Front Fender',
  'Right Front Door',
  'Right Rear Door',
  'Right Pillar Front (A)',
  'Right Pillar Center (B)',
  'Right Pillar Rear (C)',
  'Right Running Board',
  'Right Qtr. Panel',
  'Floor / Silencer',
  'Rr View Mirror (LT/RT)',
  'Tyres / Rim',
];

export const DEFAULT_GLASSES = [
  'Front Wind Shield Glass',
  'Left Front Door Glass',
  'Right Front Door Glass',
  'Left Rear Door Glass',
  'Right Rear Door Glass',
  'Rear Wind Shield Glass',
];
