/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ElectricalAccessory = IDL.Record({
  'name' : IDL.Text,
  'isWorking' : IDL.Bool,
  'remarks' : IDL.Text,
});
export const GlassStatus = IDL.Record({
  'glassName' : IDL.Text,
  'isSafe' : IDL.Bool,
  'isBroken' : IDL.Bool,
  'remarks' : IDL.Text,
});
export const NonElectricalAccessory = IDL.Record({
  'isPresent' : IDL.Bool,
  'name' : IDL.Text,
  'remarks' : IDL.Text,
});
export const PartStatus = IDL.Variant({
  'broken' : IDL.Null,
  'scratch' : IDL.Null,
  'pressed' : IDL.Null,
  'safe' : IDL.Null,
});
export const PartChecklist = IDL.Record({
  'status' : PartStatus,
  'partName' : IDL.Text,
  'remarks' : IDL.Text,
});
export const PhotoMetadata = IDL.Record({
  'watermarkText' : IDL.Text,
  'gpsCoordinates' : IDL.Text,
  'filePath' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InspectionHeader = IDL.Record({
  'customerName' : IDL.Text,
  'inspectionDate' : IDL.Text,
  'inspectionTime' : IDL.Text,
  'inspectionPlace' : IDL.Text,
  'company' : IDL.Text,
  'customerAddress' : IDL.Text,
  'recommendedForInsurance' : IDL.Bool,
  'refNo' : IDL.Text,
  'dealerAgent' : IDL.Text,
  'vehicleNo' : IDL.Text,
});
export const VehicleSpecs = IDL.Record({
  'modelVariant' : IDL.Text,
  'chassisNo' : IDL.Text,
  'color' : IDL.Text,
  'engineNo' : IDL.Text,
  'odometerReading' : IDL.Nat,
  'oldPolicyFrom' : IDL.Text,
  'yearOfManufacturing' : IDL.Text,
  'fuelType' : IDL.Variant({
    'cngLpg' : IDL.Null,
    'petrol' : IDL.Null,
    'diesel' : IDL.Null,
  }),
});
export const InspectionSummary = IDL.Record({
  'id' : IDL.Nat,
  'vehicleNumber' : IDL.Text,
  'timestamp' : IDL.Nat,
  'makeModel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalInspections' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPhotos' : IDL.Nat,
});
export const Declaration = IDL.Record({
  'proposerName' : IDL.Text,
  'signatureDate' : IDL.Text,
  'surveyorName' : IDL.Text,
});
export const PreviousInsuranceDetails = IDL.Record({
  'timeLapse' : IDL.Text,
  'insuranceCompany' : IDL.Text,
  'expiryDate' : IDL.Text,
  'numOfClaims' : IDL.Nat,
  'policyNumber' : IDL.Text,
});
export const DetailedInspection = IDL.Record({
  'id' : IDL.Nat,
  'glasses' : IDL.Vec(GlassStatus),
  'user' : IDL.Principal,
  'nonElectricalAccessories' : IDL.Vec(NonElectricalAccessory),
  'declaration' : Declaration,
  'electricalAccessories' : IDL.Vec(ElectricalAccessory),
  'timestamp' : IDL.Nat,
  'vehicleSpecs' : VehicleSpecs,
  'photos' : IDL.Vec(PhotoMetadata),
  'partsChecklist' : IDL.Vec(PartChecklist),
  'previousInsurance' : PreviousInsuranceDetails,
  'header' : InspectionHeader,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addElectricalAccessory' : IDL.Func([IDL.Nat, ElectricalAccessory], [], []),
  'addGlassStatus' : IDL.Func([IDL.Nat, GlassStatus], [], []),
  'addNonElectricalAccessory' : IDL.Func(
      [IDL.Nat, NonElectricalAccessory],
      [],
      [],
    ),
  'addPartToChecklist' : IDL.Func([IDL.Nat, PartChecklist], [], []),
  'addPhotoToDetailedInspection' : IDL.Func([IDL.Nat, PhotoMetadata], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDetailedInspection' : IDL.Func(
      [InspectionHeader, VehicleSpecs],
      [IDL.Nat],
      [],
    ),
  'getCallerInspectionSummaries' : IDL.Func(
      [],
      [IDL.Vec(InspectionSummary)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDetailedInspectionById' : IDL.Func(
      [IDL.Nat],
      [DetailedInspection],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDeclaration' : IDL.Func([IDL.Nat, Declaration], [], []),
  'updatePreviousInsurance' : IDL.Func(
      [IDL.Nat, PreviousInsuranceDetails],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ElectricalAccessory = IDL.Record({
    'name' : IDL.Text,
    'isWorking' : IDL.Bool,
    'remarks' : IDL.Text,
  });
  const GlassStatus = IDL.Record({
    'glassName' : IDL.Text,
    'isSafe' : IDL.Bool,
    'isBroken' : IDL.Bool,
    'remarks' : IDL.Text,
  });
  const NonElectricalAccessory = IDL.Record({
    'isPresent' : IDL.Bool,
    'name' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const PartStatus = IDL.Variant({
    'broken' : IDL.Null,
    'scratch' : IDL.Null,
    'pressed' : IDL.Null,
    'safe' : IDL.Null,
  });
  const PartChecklist = IDL.Record({
    'status' : PartStatus,
    'partName' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const PhotoMetadata = IDL.Record({
    'watermarkText' : IDL.Text,
    'gpsCoordinates' : IDL.Text,
    'filePath' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InspectionHeader = IDL.Record({
    'customerName' : IDL.Text,
    'inspectionDate' : IDL.Text,
    'inspectionTime' : IDL.Text,
    'inspectionPlace' : IDL.Text,
    'company' : IDL.Text,
    'customerAddress' : IDL.Text,
    'recommendedForInsurance' : IDL.Bool,
    'refNo' : IDL.Text,
    'dealerAgent' : IDL.Text,
    'vehicleNo' : IDL.Text,
  });
  const VehicleSpecs = IDL.Record({
    'modelVariant' : IDL.Text,
    'chassisNo' : IDL.Text,
    'color' : IDL.Text,
    'engineNo' : IDL.Text,
    'odometerReading' : IDL.Nat,
    'oldPolicyFrom' : IDL.Text,
    'yearOfManufacturing' : IDL.Text,
    'fuelType' : IDL.Variant({
      'cngLpg' : IDL.Null,
      'petrol' : IDL.Null,
      'diesel' : IDL.Null,
    }),
  });
  const InspectionSummary = IDL.Record({
    'id' : IDL.Nat,
    'vehicleNumber' : IDL.Text,
    'timestamp' : IDL.Nat,
    'makeModel' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalInspections' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPhotos' : IDL.Nat,
  });
  const Declaration = IDL.Record({
    'proposerName' : IDL.Text,
    'signatureDate' : IDL.Text,
    'surveyorName' : IDL.Text,
  });
  const PreviousInsuranceDetails = IDL.Record({
    'timeLapse' : IDL.Text,
    'insuranceCompany' : IDL.Text,
    'expiryDate' : IDL.Text,
    'numOfClaims' : IDL.Nat,
    'policyNumber' : IDL.Text,
  });
  const DetailedInspection = IDL.Record({
    'id' : IDL.Nat,
    'glasses' : IDL.Vec(GlassStatus),
    'user' : IDL.Principal,
    'nonElectricalAccessories' : IDL.Vec(NonElectricalAccessory),
    'declaration' : Declaration,
    'electricalAccessories' : IDL.Vec(ElectricalAccessory),
    'timestamp' : IDL.Nat,
    'vehicleSpecs' : VehicleSpecs,
    'photos' : IDL.Vec(PhotoMetadata),
    'partsChecklist' : IDL.Vec(PartChecklist),
    'previousInsurance' : PreviousInsuranceDetails,
    'header' : InspectionHeader,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addElectricalAccessory' : IDL.Func([IDL.Nat, ElectricalAccessory], [], []),
    'addGlassStatus' : IDL.Func([IDL.Nat, GlassStatus], [], []),
    'addNonElectricalAccessory' : IDL.Func(
        [IDL.Nat, NonElectricalAccessory],
        [],
        [],
      ),
    'addPartToChecklist' : IDL.Func([IDL.Nat, PartChecklist], [], []),
    'addPhotoToDetailedInspection' : IDL.Func([IDL.Nat, PhotoMetadata], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDetailedInspection' : IDL.Func(
        [InspectionHeader, VehicleSpecs],
        [IDL.Nat],
        [],
      ),
    'getCallerInspectionSummaries' : IDL.Func(
        [],
        [IDL.Vec(InspectionSummary)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDetailedInspectionById' : IDL.Func(
        [IDL.Nat],
        [DetailedInspection],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDeclaration' : IDL.Func([IDL.Nat, Declaration], [], []),
    'updatePreviousInsurance' : IDL.Func(
        [IDL.Nat, PreviousInsuranceDetails],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };