/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalInspections' : bigint,
  'totalUsers' : bigint,
  'totalPhotos' : bigint,
}
export interface Declaration {
  'proposerName' : string,
  'signatureDate' : string,
  'surveyorName' : string,
}
export interface DetailedInspection {
  'id' : bigint,
  'glasses' : Array<GlassStatus>,
  'user' : Principal,
  'nonElectricalAccessories' : Array<NonElectricalAccessory>,
  'declaration' : Declaration,
  'electricalAccessories' : Array<ElectricalAccessory>,
  'timestamp' : bigint,
  'vehicleSpecs' : VehicleSpecs,
  'photos' : Array<PhotoMetadata>,
  'partsChecklist' : Array<PartChecklist>,
  'previousInsurance' : PreviousInsuranceDetails,
  'header' : InspectionHeader,
}
export interface ElectricalAccessory {
  'name' : string,
  'isWorking' : boolean,
  'remarks' : string,
}
export interface GlassStatus {
  'glassName' : string,
  'isSafe' : boolean,
  'isBroken' : boolean,
  'remarks' : string,
}
export interface InspectionHeader {
  'customerName' : string,
  'inspectionDate' : string,
  'inspectionTime' : string,
  'inspectionPlace' : string,
  'company' : string,
  'customerAddress' : string,
  'recommendedForInsurance' : boolean,
  'refNo' : string,
  'dealerAgent' : string,
  'vehicleNo' : string,
}
export interface InspectionSummary {
  'id' : bigint,
  'vehicleNumber' : string,
  'timestamp' : bigint,
  'makeModel' : string,
}
export interface NonElectricalAccessory {
  'isPresent' : boolean,
  'name' : string,
  'remarks' : string,
}
export interface PartChecklist {
  'status' : PartStatus,
  'partName' : string,
  'remarks' : string,
}
export type PartStatus = { 'broken' : null } |
  { 'scratch' : null } |
  { 'pressed' : null } |
  { 'safe' : null };
export interface PhotoMetadata {
  'watermarkText' : string,
  'gpsCoordinates' : string,
  'filePath' : string,
  'timestamp' : bigint,
}
export interface PreviousInsuranceDetails {
  'timeLapse' : string,
  'insuranceCompany' : string,
  'expiryDate' : string,
  'numOfClaims' : bigint,
  'policyNumber' : string,
}
export interface UserProfile { 'name' : string, 'contactNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehicleSpecs {
  'modelVariant' : string,
  'chassisNo' : string,
  'color' : string,
  'engineNo' : string,
  'odometerReading' : bigint,
  'oldPolicyFrom' : string,
  'yearOfManufacturing' : string,
  'fuelType' : { 'cngLpg' : null } |
    { 'petrol' : null } |
    { 'diesel' : null },
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addElectricalAccessory' : ActorMethod<
    [bigint, ElectricalAccessory],
    undefined
  >,
  'addGlassStatus' : ActorMethod<[bigint, GlassStatus], undefined>,
  'addNonElectricalAccessory' : ActorMethod<
    [bigint, NonElectricalAccessory],
    undefined
  >,
  'addPartToChecklist' : ActorMethod<[bigint, PartChecklist], undefined>,
  'addPhotoToDetailedInspection' : ActorMethod<
    [bigint, PhotoMetadata],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDetailedInspection' : ActorMethod<
    [InspectionHeader, VehicleSpecs],
    bigint
  >,
  'getCallerInspectionSummaries' : ActorMethod<[], Array<InspectionSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDetailedInspectionById' : ActorMethod<[bigint], DetailedInspection>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDeclaration' : ActorMethod<[bigint, Declaration], undefined>,
  'updatePreviousInsurance' : ActorMethod<
    [bigint, PreviousInsuranceDetails],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];