/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ElectricalAccessory {
    name: string;
    isWorking: boolean;
    remarks: string;
}
export interface DetailedInspection {
    id: bigint;
    glasses: Array<GlassStatus>;
    user: Principal;
    nonElectricalAccessories: Array<NonElectricalAccessory>;
    declaration: Declaration;
    electricalAccessories: Array<ElectricalAccessory>;
    timestamp: bigint;
    vehicleSpecs: VehicleSpecs;
    photos: Array<PhotoMetadata>;
    partsChecklist: Array<PartChecklist>;
    previousInsurance: PreviousInsuranceDetails;
    header: InspectionHeader;
}
export interface Declaration {
    proposerName: string;
    signatureDate: string;
    surveyorName: string;
}
export interface InspectionHeader {
    customerName: string;
    inspectionDate: string;
    inspectionTime: string;
    inspectionPlace: string;
    company: string;
    customerAddress: string;
    recommendedForInsurance: boolean;
    refNo: string;
    dealerAgent: string;
    vehicleNo: string;
}
export interface PhotoMetadata {
    watermarkText: string;
    gpsCoordinates: string;
    filePath: string;
    timestamp: bigint;
}
export interface PartChecklist {
    status: PartStatus;
    partName: string;
    remarks: string;
}
export interface DashboardStats {
    totalInspections: bigint;
    totalUsers: bigint;
    totalPhotos: bigint;
}
export interface VehicleSpecs {
    modelVariant: string;
    chassisNo: string;
    color: string;
    engineNo: string;
    odometerReading: bigint;
    oldPolicyFrom: string;
    yearOfManufacturing: string;
    fuelType: Variant_cngLpg_petrol_diesel;
}
export interface GlassStatus {
    glassName: string;
    isSafe: boolean;
    isBroken: boolean;
    remarks: string;
}
export interface InspectionSummary {
    id: bigint;
    vehicleNumber: string;
    timestamp: bigint;
    makeModel: string;
}
export interface NonElectricalAccessory {
    isPresent: boolean;
    name: string;
    remarks: string;
}
export interface UserProfile {
    name: string;
    contactNumber: string;
}
export interface PreviousInsuranceDetails {
    timeLapse: string;
    insuranceCompany: string;
    expiryDate: string;
    numOfClaims: bigint;
    policyNumber: string;
}
export enum PartStatus {
    broken = "broken",
    scratch = "scratch",
    pressed = "pressed",
    safe = "safe"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cngLpg_petrol_diesel {
    cngLpg = "cngLpg",
    petrol = "petrol",
    diesel = "diesel"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addElectricalAccessory(inspectionId: bigint, accessory: ElectricalAccessory): Promise<void>;
    addGlassStatus(inspectionId: bigint, glass: GlassStatus): Promise<void>;
    addNonElectricalAccessory(inspectionId: bigint, accessory: NonElectricalAccessory): Promise<void>;
    addPartToChecklist(inspectionId: bigint, part: PartChecklist): Promise<void>;
    addPhotoToDetailedInspection(inspectionId: bigint, photo: PhotoMetadata): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDetailedInspection(header: InspectionHeader, vehicleSpecs: VehicleSpecs): Promise<bigint>;
    getCallerInspectionSummaries(): Promise<Array<InspectionSummary>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDetailedInspectionById(inspectionId: bigint): Promise<DetailedInspection>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDeclaration(inspectionId: bigint, declaration: Declaration): Promise<void>;
    updatePreviousInsurance(inspectionId: bigint, details: PreviousInsuranceDetails): Promise<void>;
}
import type { Declaration as _Declaration, DetailedInspection as _DetailedInspection, ElectricalAccessory as _ElectricalAccessory, GlassStatus as _GlassStatus, InspectionHeader as _InspectionHeader, NonElectricalAccessory as _NonElectricalAccessory, PartChecklist as _PartChecklist, PartStatus as _PartStatus, PhotoMetadata as _PhotoMetadata, PreviousInsuranceDetails as _PreviousInsuranceDetails, UserProfile as _UserProfile, UserRole as _UserRole, VehicleSpecs as _VehicleSpecs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addElectricalAccessory(arg0: bigint, arg1: ElectricalAccessory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addElectricalAccessory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addElectricalAccessory(arg0, arg1);
            return result;
        }
    }
    async addGlassStatus(arg0: bigint, arg1: GlassStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGlassStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGlassStatus(arg0, arg1);
            return result;
        }
    }
    async addNonElectricalAccessory(arg0: bigint, arg1: NonElectricalAccessory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNonElectricalAccessory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNonElectricalAccessory(arg0, arg1);
            return result;
        }
    }
    async addPartToChecklist(arg0: bigint, arg1: PartChecklist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPartToChecklist(arg0, to_candid_PartChecklist_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPartToChecklist(arg0, to_candid_PartChecklist_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPhotoToDetailedInspection(arg0: bigint, arg1: PhotoMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhotoToDetailedInspection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhotoToDetailedInspection(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDetailedInspection(arg0: InspectionHeader, arg1: VehicleSpecs): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDetailedInspection(arg0, to_candid_VehicleSpecs_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDetailedInspection(arg0, to_candid_VehicleSpecs_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerInspectionSummaries(): Promise<Array<InspectionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerInspectionSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerInspectionSummaries();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDetailedInspectionById(arg0: bigint): Promise<DetailedInspection> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetailedInspectionById(arg0);
                return from_candid_DetailedInspection_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetailedInspectionById(arg0);
            return from_candid_DetailedInspection_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDeclaration(arg0: bigint, arg1: Declaration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeclaration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeclaration(arg0, arg1);
            return result;
        }
    }
    async updatePreviousInsurance(arg0: bigint, arg1: PreviousInsuranceDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreviousInsurance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreviousInsurance(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DetailedInspection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetailedInspection): DetailedInspection {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PartChecklist_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartChecklist): PartChecklist {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PartStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartStatus): PartStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleSpecs_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleSpecs): VehicleSpecs {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    glasses: Array<_GlassStatus>;
    user: Principal;
    nonElectricalAccessories: Array<_NonElectricalAccessory>;
    declaration: _Declaration;
    electricalAccessories: Array<_ElectricalAccessory>;
    timestamp: bigint;
    vehicleSpecs: _VehicleSpecs;
    photos: Array<_PhotoMetadata>;
    partsChecklist: Array<_PartChecklist>;
    previousInsurance: _PreviousInsuranceDetails;
    header: _InspectionHeader;
}): {
    id: bigint;
    glasses: Array<GlassStatus>;
    user: Principal;
    nonElectricalAccessories: Array<NonElectricalAccessory>;
    declaration: Declaration;
    electricalAccessories: Array<ElectricalAccessory>;
    timestamp: bigint;
    vehicleSpecs: VehicleSpecs;
    photos: Array<PhotoMetadata>;
    partsChecklist: Array<PartChecklist>;
    previousInsurance: PreviousInsuranceDetails;
    header: InspectionHeader;
} {
    return {
        id: value.id,
        glasses: value.glasses,
        user: value.user,
        nonElectricalAccessories: value.nonElectricalAccessories,
        declaration: value.declaration,
        electricalAccessories: value.electricalAccessories,
        timestamp: value.timestamp,
        vehicleSpecs: from_candid_VehicleSpecs_n15(_uploadFile, _downloadFile, value.vehicleSpecs),
        photos: value.photos,
        partsChecklist: from_candid_vec_n18(_uploadFile, _downloadFile, value.partsChecklist),
        previousInsurance: value.previousInsurance,
        header: value.header
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    modelVariant: string;
    chassisNo: string;
    color: string;
    engineNo: string;
    odometerReading: bigint;
    oldPolicyFrom: string;
    yearOfManufacturing: string;
    fuelType: {
        cngLpg: null;
    } | {
        petrol: null;
    } | {
        diesel: null;
    };
}): {
    modelVariant: string;
    chassisNo: string;
    color: string;
    engineNo: string;
    odometerReading: bigint;
    oldPolicyFrom: string;
    yearOfManufacturing: string;
    fuelType: Variant_cngLpg_petrol_diesel;
} {
    return {
        modelVariant: value.modelVariant,
        chassisNo: value.chassisNo,
        color: value.color,
        engineNo: value.engineNo,
        odometerReading: value.odometerReading,
        oldPolicyFrom: value.oldPolicyFrom,
        yearOfManufacturing: value.yearOfManufacturing,
        fuelType: from_candid_variant_n17(_uploadFile, _downloadFile, value.fuelType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PartStatus;
    partName: string;
    remarks: string;
}): {
    status: PartStatus;
    partName: string;
    remarks: string;
} {
    return {
        status: from_candid_PartStatus_n21(_uploadFile, _downloadFile, value.status),
        partName: value.partName,
        remarks: value.remarks
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cngLpg: null;
} | {
    petrol: null;
} | {
    diesel: null;
}): Variant_cngLpg_petrol_diesel {
    return "cngLpg" in value ? Variant_cngLpg_petrol_diesel.cngLpg : "petrol" in value ? Variant_cngLpg_petrol_diesel.petrol : "diesel" in value ? Variant_cngLpg_petrol_diesel.diesel : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    broken: null;
} | {
    scratch: null;
} | {
    pressed: null;
} | {
    safe: null;
}): PartStatus {
    return "broken" in value ? PartStatus.broken : "scratch" in value ? PartStatus.scratch : "pressed" in value ? PartStatus.pressed : "safe" in value ? PartStatus.safe : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PartChecklist>): Array<PartChecklist> {
    return value.map((x)=>from_candid_PartChecklist_n19(_uploadFile, _downloadFile, x));
}
function to_candid_PartChecklist_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartChecklist): _PartChecklist {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PartStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartStatus): _PartStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleSpecs_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleSpecs): _VehicleSpecs {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PartStatus;
    partName: string;
    remarks: string;
}): {
    status: _PartStatus;
    partName: string;
    remarks: string;
} {
    return {
        status: to_candid_PartStatus_n3(_uploadFile, _downloadFile, value.status),
        partName: value.partName,
        remarks: value.remarks
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    modelVariant: string;
    chassisNo: string;
    color: string;
    engineNo: string;
    odometerReading: bigint;
    oldPolicyFrom: string;
    yearOfManufacturing: string;
    fuelType: Variant_cngLpg_petrol_diesel;
}): {
    modelVariant: string;
    chassisNo: string;
    color: string;
    engineNo: string;
    odometerReading: bigint;
    oldPolicyFrom: string;
    yearOfManufacturing: string;
    fuelType: {
        cngLpg: null;
    } | {
        petrol: null;
    } | {
        diesel: null;
    };
} {
    return {
        modelVariant: value.modelVariant,
        chassisNo: value.chassisNo,
        color: value.color,
        engineNo: value.engineNo,
        odometerReading: value.odometerReading,
        oldPolicyFrom: value.oldPolicyFrom,
        yearOfManufacturing: value.yearOfManufacturing,
        fuelType: to_candid_variant_n9(_uploadFile, _downloadFile, value.fuelType)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartStatus): {
    broken: null;
} | {
    scratch: null;
} | {
    pressed: null;
} | {
    safe: null;
} {
    return value == PartStatus.broken ? {
        broken: null
    } : value == PartStatus.scratch ? {
        scratch: null
    } : value == PartStatus.pressed ? {
        pressed: null
    } : value == PartStatus.safe ? {
        safe: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cngLpg_petrol_diesel): {
    cngLpg: null;
} | {
    petrol: null;
} | {
    diesel: null;
} {
    return value == Variant_cngLpg_petrol_diesel.cngLpg ? {
        cngLpg: null
    } : value == Variant_cngLpg_petrol_diesel.petrol ? {
        petrol: null
    } : value == Variant_cngLpg_petrol_diesel.diesel ? {
        diesel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
